version: "3.3"
    
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file: .env
